# Generated by Django 4.2.2 on 2023-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H20Hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='h20user',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='h20user',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='h20user',
            name='meter_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='h20user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
